/**
 * Paystack integration service.
 *
 * Docs: https://paystack.com/docs/api/
 * Test cards: https://paystack.com/docs/payments/test-payments/
 *
 * All amounts are in KOBO (1 NGN = 100 kobo) as required by the Paystack API.
 */
import crypto from 'crypto';

const BASE_URL = 'https://api.paystack.co';

function getSecretKey(): string {
  const key = process.env.PAYSTACK_SECRET_KEY;
  if (!key) throw new Error('PAYSTACK_SECRET_KEY is not configured');
  return key;
}

/** Returns true when Paystack is configured and available in this environment. */
export function isPaystackEnabled(): boolean {
  return Boolean(process.env.PAYSTACK_SECRET_KEY);
}

// ── Types ─────────────────────────────────────────────────────────────────────

export interface InitializeParams {
  /** Customer email — Paystack sends a receipt here */
  email: string;
  /** Amount in kobo */
  amountKobo: number;
  /** Unique reference generated by us (UUID) */
  reference: string;
  /** URL Paystack redirects the customer to after payment */
  callbackUrl: string;
  /** Arbitrary data Paystack echoes back in the webhook */
  metadata?: Record<string, unknown>;
}

export interface InitializeResult {
  authorizationUrl: string;
  accessCode: string;
  reference: string;
}

export interface VerifyResult {
  status: 'success' | 'failed' | 'abandoned' | 'reversed';
  reference: string;
  /** Amount actually paid, in kobo */
  amountKobo: number;
  customer: { email: string; name: string };
  metadata: Record<string, unknown>;
  paidAt: string | null;
}

// ── API helpers ───────────────────────────────────────────────────────────────

async function paystackPost<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${getSecretKey()}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });

  const json = (await res.json()) as { status: boolean; message: string; data: T };
  if (!json.status) throw new Error(`Paystack error: ${json.message}`);
  return json.data;
}

async function paystackGet<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { Authorization: `Bearer ${getSecretKey()}` },
  });

  const json = (await res.json()) as { status: boolean; message: string; data: T };
  if (!json.status) throw new Error(`Paystack error: ${json.message}`);
  return json.data;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Creates a Paystack payment session and returns the hosted checkout URL.
 * The customer is redirected there to complete payment.
 */
export async function initializeTransaction(
  params: InitializeParams
): Promise<InitializeResult> {
  const raw = await paystackPost<{
    authorization_url: string;
    access_code: string;
    reference: string;
  }>('/transaction/initialize', {
    email: params.email,
    amount: params.amountKobo,
    reference: params.reference,
    callback_url: params.callbackUrl,
    metadata: params.metadata ?? {},
    currency: 'NGN',
    channels: ['card', 'bank', 'bank_transfer', 'ussd', 'qr'],
  });

  return {
    authorizationUrl: raw.authorization_url,
    accessCode: raw.access_code,
    reference: raw.reference,
  };
}

/**
 * Verifies the final status of a Paystack transaction.
 * Call this from the callback URL handler as a fallback to the webhook.
 */
export async function verifyTransaction(reference: string): Promise<VerifyResult> {
  const raw = await paystackGet<{
    status: string;
    reference: string;
    amount: number;
    customer: { email: string; first_name: string; last_name: string };
    metadata: Record<string, unknown>;
    paid_at: string | null;
  }>(`/transaction/verify/${encodeURIComponent(reference)}`);

  const status = raw.status as VerifyResult['status'];
  return {
    status,
    reference: raw.reference,
    amountKobo: raw.amount,
    customer: {
      email: raw.customer.email,
      name: [raw.customer.first_name, raw.customer.last_name].filter(Boolean).join(' '),
    },
    metadata: raw.metadata ?? {},
    paidAt: raw.paid_at,
  };
}

/**
 * Validates a Paystack webhook signature.
 *
 * Paystack signs the raw request body with HMAC-SHA512 using the secret key
 * and passes it in the `x-paystack-signature` header.
 *
 * IMPORTANT: pass the RAW request body as a string/Buffer — not the parsed JSON.
 */
export function validateWebhookSignature(
  rawBody: string | Buffer,
  signature: string
): boolean {
  const key = process.env.PAYSTACK_SECRET_KEY;
  if (!key) return false;

  const expected = crypto
    .createHmac('sha512', key)
    .update(rawBody)
    .digest('hex');

  return crypto.timingSafeEqual(
    Buffer.from(expected, 'hex'),
    Buffer.from(signature, 'hex')
  );
}
