/** A normalized webhook event from any provider. */
export interface BillingWebhookEvent {
  /** 'success' = payment completed; anything else we ignore for now */
  type: 'success' | 'other';
  /** Our checkout reference (echoed back by the provider) */
  reference: string;
  /** Metadata we attached at checkout time ({ workspaceId, planKey }) */
  metadata: Record<string, unknown>;
}

export interface CheckoutArgs {
  workspaceId: string;
  planKey: string;
  amountMinor: number;   // minor units of `currency`
  currency: string;
  email: string;
  reference: string;     // unique, generated by us
  callbackUrl: string;   // where the provider returns the user
  productName: string;   // shown on the hosted checkout
}

export interface PaymentProvider {
  readonly name: 'paystack' | 'stripe';
  isConfigured(): boolean;
  /** Creates a hosted checkout session and returns its URL. */
  createCheckout(args: CheckoutArgs): Promise<{ url: string }>;
  /** Verifies + normalizes a webhook; returns null if invalid/unrecognized. */
  parseWebhook(rawBody: string | Buffer, signature: string | undefined): Promise<BillingWebhookEvent | null>;
}
